/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tylernelson
 */

public class PsychicGame3
{
	//Attributes
	
	//a.	Input
	//- p1: an object from Player class.
	private Player p1;
	private Player p2;
	private Player p3;
	
	//- originalNumber: a number generated randomly by a computer will be compared to
	// a guessedNumber generated by a player. */
	private int originalNumber;
	
	//Constructors
	public PsychicGame3()
	{
		//initialize an object of Player class
		p1 = new Player();
		p2 = new Player();
		p3 = new Player();
		//then initialize the originalNumber as 0.
		originalNumber = 0;
	}
	
	//Methods
	public void play()
	{
		do
		{
			//assign a computer-generated random number from 1 to 6 to the originalNumber
			originalNumber = (int)(Math.random()*6)+1;
		
			//display a message, “ The computer has chosen the number originalNumber”
			System.out.println("The computer has chosen the number " + originalNumber);

			//lets the Player class object pick its number,
			p1.play();
		
			//then compare these two numbers. If the numbers are matched, then
			if (p1.getGuessedNumber() == originalNumber)
			{
				//display a message, “player’s nickname has won.”
				System.out.println(p1.getNickName() + " has won.");
			}
			else 
			{
				//or “No one has won this time.”
				System.out.println("No one has won this time.");
			}
			
			//lets the Player class object pick its number,
			p2.play();
		
			//then compare these two numbers. If the numbers are matched, then
			if (p2.getGuessedNumber() == originalNumber)
			{
				//display a message, “player’s nickname has won.”
				System.out.println(p2.getNickName() + " has won.");
			}
			else 
			{
				//or “No one has won this time.”
				System.out.println("No one has won this time.");
			}
			
			//lets the Player class object pick its number,
			p3.play();
		
			//then compare these two numbers. If the numbers are matched, then
			if (p3.getGuessedNumber() == originalNumber)
			{
				//display a message, “player’s nickname has won.”
				System.out.println(p3.getNickName() + " has won.");
			}
			else 
			{
				//or “No one has won this time.”
				System.out.println("No one has won this time.");
			}
			
		} while (originalNumber != p1.getGuessedNumber() && originalNumber != p2.getGuessedNumber() && originalNumber != p3.getGuessedNumber());
	}
}